# Generated by Django 4.2.7 on 2023-12-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='author',
        ),
    ]
