# Generated by Django 4.2.7 on 2023-12-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
