# Generated by Django 4.2.7 on 2023-12-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_comentarios_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='signature',
            field=models.CharField(default='Firma', max_length=50),
        ),
    ]
