# Generated by Django 5.0 on 2023-12-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0004_comentarios_signature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comentarios',
            new_name='comentario',
        ),
    ]
